const { db, initDatabase } = require('./db');

// Initialize database
initDatabase();

// Clear existing data
db.data.doctors = [];
db.data.hospitals = [];
db.data.users = [];
db.data.consultations = [];
db.data.health_records = [];
db.data.emergency_requests = [];
db.data.ai_chat_history = [];

const doctors = [
  {
    name: "Dr. Priya Sharma",
    specialization: "General Physician",
    qualification: "MBBS, MD",
    experience_years: 12,
    hospital: "Apollo Hospitals",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    languages: JSON.stringify(["Tamil", "English", "Hindi"]),
    consultation_fee: 299,
    rating: 4.8,
    total_reviews: 1243,
    available_today: 1,
    next_slot: "Today 3:30 PM",
    photo_url: "/images/Dr. Priya Sharma.jpg",
    bio: "Experienced general physician with expertise in preventive care and chronic disease management.",
    is_online: 1
  },
  {
    name: "Dr. Rajesh Kumar",
    specialization: "Cardiologist",
    qualification: "MBBS, DM Cardiology",
    experience_years: 18,
    hospital: "AIIMS Delhi",
    location: "New Delhi",
    state: "Delhi",
    languages: JSON.stringify(["Hindi", "English"]),
    consultation_fee: 799,
    rating: 4.9,
    total_reviews: 2108,
    available_today: 1,
    next_slot: "Today 5:00 PM",
    photo_url: "/images/rajeshkumar.webp",
    bio: "Leading cardiologist specializing in interventional cardiology and heart failure management.",
    is_online: 1
  },
  {
    name: "Dr. Meena Patel",
    specialization: "Pediatrician",
    qualification: "MBBS, MD Pediatrics",
    experience_years: 9,
    hospital: "Narayana Health",
    location: "Ahmedabad, Gujarat",
    state: "Gujarat",
    languages: JSON.stringify(["Gujarati", "Hindi", "English"]),
    consultation_fee: 399,
    rating: 4.7,
    total_reviews: 876,
    available_today: 1,
    next_slot: "Today 4:00 PM",
    photo_url: "",
    bio: "Child specialist focused on pediatric nutrition, growth monitoring, and developmental disorders.",
    is_online: 1
  },
  {
    name: "Dr. Suresh Nair",
    specialization: "Orthopedic Surgeon",
    qualification: "MBBS, MS Ortho",
    experience_years: 15,
    hospital: "Amrita Hospital",
    location: "Kochi, Kerala",
    state: "Kerala",
    languages: JSON.stringify(["Malayalam", "English"]),
    consultation_fee: 599,
    rating: 4.6,
    total_reviews: 654,
    available_today: 0,
    next_slot: "Tomorrow 10:00 AM",
    photo_url: "",
    bio: "Orthopedic surgeon specializing in joint replacement and sports medicine.",
    is_online: 0
  },
  {
    name: "Dr. Ananya Iyer",
    specialization: "Dermatologist",
    qualification: "MBBS, MD Dermatology",
    experience_years: 7,
    hospital: "Manipal Hospital",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    languages: JSON.stringify(["Kannada", "Tamil", "English"]),
    consultation_fee: 499,
    rating: 4.8,
    total_reviews: 1432,
    available_today: 1,
    next_slot: "Today 6:00 PM",
    photo_url: "/images/Dr. Ananya Iyer.jpeg",
    bio: "Dermatologist expert in treating skin conditions, hair disorders, and cosmetic procedures.",
    is_online: 1
  },
  {
    name: "Dr. Vikram Singh",
    specialization: "Neurologist",
    qualification: "MBBS, DM Neurology",
    experience_years: 20,
    hospital: "Fortis Hospital",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    languages: JSON.stringify(["Marathi", "Hindi", "English"]),
    consultation_fee: 999,
    rating: 4.9,
    total_reviews: 987,
    available_today: 1,
    next_slot: "Today 7:00 PM",
    photo_url: "/images/vikramkumar.webp",
    bio: "Neurologist specializing in stroke management, epilepsy, and movement disorders.",
    is_online: 1
  },
  {
    name: "Dr. Lakshmi Devi",
    specialization: "Gynecologist",
    qualification: "MBBS, MS OBG",
    experience_years: 14,
    hospital: "Rainbow Hospital",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    languages: JSON.stringify(["Telugu", "Hindi", "English"]),
    consultation_fee: 499,
    rating: 4.7,
    total_reviews: 2341,
    available_today: 1,
    next_slot: "Today 2:00 PM",
    photo_url: "",
    bio: "Gynecologist with expertise in high-risk pregnancies and fertility treatments.",
    is_online: 1
  },
  {
    name: "Dr. Arjun Reddy",
    specialization: "Diabetologist",
    qualification: "MBBS, MD Internal Medicine",
    experience_years: 11,
    hospital: "Care Hospital",
    location: "Vijayawada, Andhra Pradesh",
    state: "Andhra Pradesh",
    languages: JSON.stringify(["Telugu", "English"]),
    consultation_fee: 349,
    rating: 4.6,
    total_reviews: 765,
    available_today: 1,
    next_slot: "Today 4:30 PM",
    photo_url: "",
    bio: "Diabetes specialist focusing on Type 1, Type 2 diabetes and metabolic disorders.",
    is_online: 1
  },
  {
    name: "Dr. Pooja Mishra",
    specialization: "Psychiatrist",
    qualification: "MBBS, MD Psychiatry",
    experience_years: 8,
    hospital: "NIMHANS",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    languages: JSON.stringify(["Hindi", "Kannada", "English"]),
    consultation_fee: 699,
    rating: 4.8,
    total_reviews: 432,
    available_today: 0,
    next_slot: "Tomorrow 11:00 AM",
    photo_url: "/images/Dr. Pooja Mishra.webp",
    bio: "Mental health expert specializing in anxiety, depression, and stress management.",
    is_online: 0
  },
  {
    name: "Dr. Mohammed Irfan",
    specialization: "ENT Specialist",
    qualification: "MBBS, MS ENT",
    experience_years: 13,
    hospital: "KIMS Hospital",
    location: "Bhubaneswar, Odisha",
    state: "Odisha",
    languages: JSON.stringify(["Odia", "Hindi", "English"]),
    consultation_fee: 399,
    rating: 4.5,
    total_reviews: 543,
    available_today: 1,
    next_slot: "Today 5:30 PM",
    photo_url: "",
    bio: "ENT specialist treating ear, nose, throat conditions and hearing disorders.",
    is_online: 1
  },
  {
    name: "Dr. Sanjay Gupta",
    specialization: "Pulmonologist",
    qualification: "MBBS, MD Pulmonology",
    experience_years: 16,
    hospital: "Max Hospital",
    location: "New Delhi",
    state: "Delhi",
    languages: JSON.stringify(["Hindi", "English", "Punjabi"]),
    consultation_fee: 649,
    rating: 4.7,
    total_reviews: 1123,
    available_today: 1,
    next_slot: "Today 3:00 PM",
    photo_url: "",
    bio: "Lung specialist treating asthma, COPD, and respiratory infections.",
    is_online: 1
  },
  {
    name: "Dr. Kavita Rao",
    specialization: "Gastroenterologist",
    qualification: "MBBS, DM Gastroenterology",
    experience_years: 12,
    hospital: "Global Hospitals",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    languages: JSON.stringify(["Tamil", "English"]),
    consultation_fee: 599,
    rating: 4.6,
    total_reviews: 789,
    available_today: 1,
    next_slot: "Today 6:30 PM",
    photo_url: "/images/Dr. Priya Sharma.jpg",
    bio: "Digestive health expert treating liver, stomach, and intestinal conditions.",
    is_online: 1
  },
  {
    name: "Dr. Amit Shah",
    specialization: "Nephrologist",
    qualification: "MBBS, DM Nephrology",
    experience_years: 19,
    hospital: "CMC Vellore",
    location: "Vellore, Tamil Nadu",
    state: "Tamil Nadu",
    languages: JSON.stringify(["Tamil", "English", "Hindi"]),
    consultation_fee: 749,
    rating: 4.8,
    total_reviews: 892,
    available_today: 0,
    next_slot: "Tomorrow 9:00 AM",
    photo_url: "/images/Dr. Amit Shah.jpg",
    bio: "Kidney specialist managing chronic kidney disease and dialysis patients.",
    is_online: 0
  },
  {
    name: "Dr. Ritu Verma",
    specialization: "Oncologist",
    qualification: "MBBS, MD Oncology",
    experience_years: 14,
    hospital: "Tata Memorial",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    languages: JSON.stringify(["Hindi", "Marathi", "English"]),
    consultation_fee: 899,
    rating: 4.9,
    total_reviews: 1456,
    available_today: 1,
    next_slot: "Today 4:00 PM",
    photo_url: "/images/rituverma.jpg",
    bio: "Cancer specialist providing chemotherapy and immunotherapy treatments.",
    is_online: 1
  },
  {
    name: "Dr. Karthik Menon",
    specialization: "Ophthalmologist",
    qualification: "MBBS, MS Ophthalmology",
    experience_years: 10,
    hospital: "Aravind Eye Hospital",
    location: "Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    languages: JSON.stringify(["Tamil", "English"]),
    consultation_fee: 349,
    rating: 4.7,
    total_reviews: 2134,
    available_today: 1,
    next_slot: "Today 2:30 PM",
    photo_url: "",
    bio: "Eye specialist treating cataracts, glaucoma, and vision problems.",
    is_online: 1
  },
  {
    name: "Dr. Neha Sharma",
    specialization: "Dentist",
    qualification: "BDS, MDS",
    experience_years: 6,
    hospital: "Dental Care Center",
    location: "Jaipur, Rajasthan",
    state: "Rajasthan",
    languages: JSON.stringify(["Hindi", "Rajasthani", "English"]),
    consultation_fee: 249,
    rating: 4.5,
    total_reviews: 567,
    available_today: 1,
    next_slot: "Today 5:00 PM",
    photo_url: "",
    bio: "Dental surgeon specializing in root canals, implants, and cosmetic dentistry.",
    is_online: 1
  },
  {
    name: "Dr. Pradeep Kumar",
    specialization: "Physiotherapist",
    qualification: "BPT, MPT",
    experience_years: 8,
    hospital: "PhysioCare Clinic",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    languages: JSON.stringify(["Marathi", "Hindi", "English"]),
    consultation_fee: 299,
    rating: 4.6,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 6:00 PM",
    photo_url: "/images/tarunmehta.jpg",
    bio: "Physical therapy expert for sports injuries, rehabilitation, and pain management.",
    is_online: 1
  },
  {
    name: "Dr. Sunita Devi",
    specialization: "Endocrinologist",
    qualification: "MBBS, DM Endocrinology",
    experience_years: 17,
    hospital: "Medanta Hospital",
    location: "Gurgaon, Haryana",
    state: "Haryana",
    languages: JSON.stringify(["Hindi", "English", "Punjabi"]),
    consultation_fee: 849,
    rating: 4.8,
    total_reviews: 723,
    available_today: 1,
    next_slot: "Today 7:30 PM",
    photo_url: "/images/Dr. Sunita Devi.jpg",
    bio: "Hormone specialist treating thyroid, diabetes, and metabolic disorders.",
    is_online: 1
  },
  {
    name: "Dr. Ramesh Chandra",
    specialization: "Rheumatologist",
    qualification: "MBBS, DM Rheumatology",
    experience_years: 13,
    hospital: "Sankara Nethralaya",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    languages: JSON.stringify(["Tamil", "English"]),
    consultation_fee: 699,
    rating: 4.6,
    total_reviews: 334,
    available_today: 0,
    next_slot: "Tomorrow 10:30 AM",
    photo_url: "",
    bio: "Arthritis and autoimmune disease specialist.",
    is_online: 0
  },
  {
    name: "Dr. Fatima Begum",
    specialization: "Hematologist",
    qualification: "MBBS, DM Hematology",
    experience_years: 11,
    hospital: "Christian Medical College",
    location: "Ludhiana, Punjab",
    state: "Punjab",
    languages: JSON.stringify(["Punjabi", "Hindi", "English"]),
    consultation_fee: 599,
    rating: 4.7,
    total_reviews: 289,
    available_today: 1,
    next_slot: "Today 3:45 PM",
    photo_url: "",
    bio: "Blood disorders specialist treating anemia, leukemia, and clotting disorders.",
    is_online: 1
  },
  {
    name: "Dr. Venkatesh Iyer",
    specialization: "Urologist",
    qualification: "MBBS, MCh Urology",
    experience_years: 15,
    hospital: "Apollo Hospitals",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    languages: JSON.stringify(["Telugu", "English", "Hindi"]),
    consultation_fee: 649,
    rating: 4.5,
    total_reviews: 678,
    available_today: 1,
    next_slot: "Today 5:15 PM",
    photo_url: "",
    bio: "Urinary tract and male reproductive health specialist.",
    is_online: 1
  },
  {
    name: "Dr. Anjali Desai",
    specialization: "General Physician",
    qualification: "MBBS, MD",
    experience_years: 9,
    hospital: "Sterling Hospital",
    location: "Ahmedabad, Gujarat",
    state: "Gujarat",
    languages: JSON.stringify(["Gujarati", "Hindi", "English"]),
    consultation_fee: 279,
    rating: 4.6,
    total_reviews: 923,
    available_today: 1,
    next_slot: "Today 4:45 PM",
    photo_url: "",
    bio: "Primary care physician with holistic approach to family health.",
    is_online: 1
  },
  {
    name: "Dr. Manoj Tiwari",
    specialization: "Cardiologist",
    qualification: "MBBS, DM Cardiology",
    experience_years: 22,
    hospital: "Fortis Escorts",
    location: "Kolkata, West Bengal",
    state: "West Bengal",
    languages: JSON.stringify(["Bengali", "Hindi", "English"]),
    consultation_fee: 899,
    rating: 4.8,
    total_reviews: 1567,
    available_today: 0,
    next_slot: "Tomorrow 11:30 AM",
    photo_url: "",
    bio: "Senior cardiologist with expertise in cardiac surgery planning.",
    is_online: 0
  },
  {
    name: "Dr. Shalini Gupta",
    specialization: "Pediatrician",
    qualification: "MBBS, MD Pediatrics",
    experience_years: 7,
    hospital: "Child Care Hospital",
    location: "Lucknow, Uttar Pradesh",
    state: "Uttar Pradesh",
    languages: JSON.stringify(["Hindi", "Urdu", "English"]),
    consultation_fee: 349,
    rating: 4.7,
    total_reviews: 678,
    available_today: 1,
    next_slot: "Today 6:15 PM",
    photo_url: "",
    bio: "Child health specialist focusing on immunization and growth monitoring.",
    is_online: 1
  },
  {
    name: "Dr. Joseph Mathew",
    specialization: "Orthopedic Surgeon",
    qualification: "MBBS, MS Ortho",
    experience_years: 18,
    hospital: "Baby Memorial",
    location: "Kozhikode, Kerala",
    state: "Kerala",
    languages: JSON.stringify(["Malayalam", "English"]),
    consultation_fee: 699,
    rating: 4.7,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 2:45 PM",
    photo_url: "",
    bio: "Joint replacement surgeon with 5000+ successful surgeries.",
    is_online: 1
  },
  {
    name: "Dr. Deepika Reddy",
    specialization: "Dermatologist",
    qualification: "MBBS, MD Dermatology",
    experience_years: 8,
    hospital: "Yashoda Hospital",
    location: "Secunderabad, Telangana",
    state: "Telangana",
    languages: JSON.stringify(["Telugu", "Hindi", "English"]),
    consultation_fee: 449,
    rating: 4.6,
    total_reviews: 1123,
    available_today: 1,
    next_slot: "Today 7:00 PM",
    photo_url: "",
    bio: "Skin and hair care expert with modern treatment techniques.",
    is_online: 1
  },
  {
    name: "Dr. Rahul Bose",
    specialization: "Neurologist",
    qualification: "MBBS, DM Neurology",
    experience_years: 16,
    hospital: "Peerless Hospital",
    location: "Kolkata, West Bengal",
    state: "West Bengal",
    languages: JSON.stringify(["Bengali", "English", "Hindi"]),
    consultation_fee: 849,
    rating: 4.8,
    total_reviews: 556,
    available_today: 1,
    next_slot: "Today 4:30 PM",
    photo_url: "",
    bio: "Brain and nervous system specialist treating migraines and seizures.",
    is_online: 1
  },
  {
    name: "Dr. Meera Krishnan",
    specialization: "Gynecologist",
    qualification: "MBBS, MS OBG",
    experience_years: 12,
    hospital: "PSG Hospital",
    location: "Coimbatore, Tamil Nadu",
    state: "Tamil Nadu",
    languages: JSON.stringify(["Tamil", "English"]),
    consultation_fee: 449,
    rating: 4.7,
    total_reviews: 1567,
    available_today: 1,
    next_slot: "Today 3:15 PM",
    photo_url: "",
    bio: "Women's health expert specializing in PCOS and fertility.",
    is_online: 1
  },
  {
    name: "Dr. Alok Ranjan",
    specialization: "Diabetologist",
    qualification: "MBBS, MD Internal Medicine",
    experience_years: 14,
    hospital: "Patna Medical College",
    location: "Patna, Bihar",
    state: "Bihar",
    languages: JSON.stringify(["Hindi", "Bhojpuri", "English"]),
    consultation_fee: 299,
    rating: 4.5,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 5:45 PM",
    photo_url: "",
    bio: "Diabetes educator helping patients manage blood sugar effectively.",
    is_online: 1
  },
  {
    name: "Dr. Nandini Sharma",
    specialization: "Psychiatrist",
    qualification: "MBBS, MD Psychiatry",
    experience_years: 10,
    hospital: "SMS Hospital",
    location: "Jaipur, Rajasthan",
    state: "Rajasthan",
    languages: JSON.stringify(["Hindi", "Rajasthani", "English"]),
    consultation_fee: 599,
    rating: 4.7,
    total_reviews: 334,
    available_today: 0,
    next_slot: "Tomorrow 9:30 AM",
    photo_url: "",
    bio: "Mental wellness advocate treating depression, anxiety, and addiction.",
    is_online: 0
  },
  {
    name: "Dr. Harish Rawat",
    specialization: "ENT Specialist",
    qualification: "MBBS, MS ENT",
    experience_years: 11,
    hospital: "AIIMS Rishikesh",
    location: "Rishikesh, Uttarakhand",
    state: "Uttarakhand",
    languages: JSON.stringify(["Hindi", "Garhwali", "English"]),
    consultation_fee: 349,
    rating: 4.6,
    total_reviews: 223,
    available_today: 1,
    next_slot: "Today 6:30 PM",
    photo_url: "",
    bio: "ENT surgeon specializing in sinus surgery and hearing restoration.",
    is_online: 1
  },
  {
    name: "Dr. Sneha Patil",
    specialization: "Pulmonologist",
    qualification: "MBBS, MD Pulmonology",
    experience_years: 9,
    hospital: "Ruby Hall Clinic",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    languages: JSON.stringify(["Marathi", "Hindi", "English"]),
    consultation_fee: 549,
    rating: 4.7,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 4:00 PM",
    photo_url: "",
    bio: "Respiratory medicine expert treating asthma and sleep apnea.",
    is_online: 1
  },
  {
    name: "Dr. Gopal Krishnan",
    specialization: "Gastroenterologist",
    qualification: "MBBS, DM Gastroenterology",
    experience_years: 20,
    hospital: "Lakeshore Hospital",
    location: "Kochi, Kerala",
    state: "Kerala",
    languages: JSON.stringify(["Malayalam", "English", "Tamil"]),
    consultation_fee: 699,
    rating: 4.8,
    total_reviews: 667,
    available_today: 1,
    next_slot: "Today 7:15 PM",
    photo_url: "",
    bio: "Digestive system specialist with expertise in endoscopy procedures.",
    is_online: 1
  },
  {
    name: "Dr. Priyanka Singh",
    specialization: "Nephrologist",
    qualification: "MBBS, DM Nephrology",
    experience_years: 13,
    hospital: "King George Hospital",
    location: "Visakhapatnam, Andhra Pradesh",
    state: "Andhra Pradesh",
    languages: JSON.stringify(["Telugu", "Hindi", "English"]),
    consultation_fee: 599,
    rating: 4.6,
    total_reviews: 334,
    available_today: 1,
    next_slot: "Today 3:30 PM",
    photo_url: "",
    bio: "Kidney care specialist managing dialysis and transplant patients.",
    is_online: 1
  },
  {
    name: "Dr. Tarun Mehta",
    specialization: "Oncologist",
    qualification: "MBBS, MD Oncology",
    experience_years: 17,
    hospital: "HCG Cancer Center",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    languages: JSON.stringify(["Hindi", "Kannada", "English"]),
    consultation_fee: 999,
    rating: 4.9,
    total_reviews: 889,
    available_today: 0,
    next_slot: "Tomorrow 10:00 AM",
    photo_url: "",
    bio: "Cancer treatment expert with focus on personalized medicine.",
    is_online: 0
  },
  {
    name: "Dr. Lakshmi Narayan",
    specialization: "Ophthalmologist",
    qualification: "MBBS, MS Ophthalmology",
    experience_years: 14,
    hospital: "LV Prasad Eye Institute",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    languages: JSON.stringify(["Telugu", "English", "Hindi"]),
    consultation_fee: 399,
    rating: 4.8,
    total_reviews: 2234,
    available_today: 1,
    next_slot: "Today 5:00 PM",
    photo_url: "",
    bio: "Eye surgeon specializing in LASIK and cataract surgery.",
    is_online: 1
  },
  {
    name: "Dr. Ritu Agarwal",
    specialization: "Dentist",
    qualification: "BDS, MDS Orthodontics",
    experience_years: 8,
    hospital: "Dental Solutions",
    location: "Indore, Madhya Pradesh",
    state: "Madhya Pradesh",
    languages: JSON.stringify(["Hindi", "English"]),
    consultation_fee: 299,
    rating: 4.6,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 6:45 PM",
    photo_url: "",
    bio: "Orthodontist specializing in braces and teeth alignment.",
    is_online: 1
  },
  {
    name: "Dr. Suresh Yadav",
    specialization: "Physiotherapist",
    qualification: "BPT, MPT Sports",
    experience_years: 7,
    hospital: "Sports Medicine Center",
    location: "Chandigarh",
    state: "Chandigarh",
    languages: JSON.stringify(["Hindi", "Punjabi", "English"]),
    consultation_fee: 349,
    rating: 4.7,
    total_reviews: 223,
    available_today: 1,
    next_slot: "Today 4:15 PM",
    photo_url: "",
    bio: "Sports physiotherapist helping athletes recover from injuries.",
    is_online: 1
  },
  {
    name: "Dr. Ananya Chatterjee",
    specialization: "Endocrinologist",
    qualification: "MBBS, DM Endocrinology",
    experience_years: 12,
    hospital: "AMRI Hospital",
    location: "Kolkata, West Bengal",
    state: "West Bengal",
    languages: JSON.stringify(["Bengali", "Hindi", "English"]),
    consultation_fee: 649,
    rating: 4.7,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 7:45 PM",
    photo_url: "",
    bio: "Hormone disorder specialist treating thyroid and PCOS.",
    is_online: 1
  },
  {
    name: "Dr. Vijay Kumar",
    specialization: "Rheumatologist",
    qualification: "MBBS, DM Rheumatology",
    experience_years: 15,
    hospital: "Osmania Hospital",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    languages: JSON.stringify(["Telugu", "Hindi", "English", "Urdu"]),
    consultation_fee: 599,
    rating: 4.5,
    total_reviews: 278,
    available_today: 0,
    next_slot: "Tomorrow 11:00 AM",
    photo_url: "",
    bio: "Autoimmune disease expert treating arthritis and lupus.",
    is_online: 0
  },
  {
    name: "Dr. Sangeeta Rani",
    specialization: "Hematologist",
    qualification: "MBBS, DM Hematology",
    experience_years: 10,
    hospital: "Rajiv Gandhi Hospital",
    location: "Raipur, Chhattisgarh",
    state: "Chhattisgarh",
    languages: JSON.stringify(["Hindi", "Chhattisgarhi", "English"]),
    consultation_fee: 499,
    rating: 4.6,
    total_reviews: 189,
    available_today: 1,
    next_slot: "Today 5:30 PM",
    photo_url: "",
    bio: "Blood disorder specialist with expertise in bone marrow disorders.",
    is_online: 1
  },
  {
    name: "Dr. Prakash Jha",
    specialization: "Urologist",
    qualification: "MBBS, MCh Urology",
    experience_years: 19,
    hospital: "IGIMS",
    location: "Patna, Bihar",
    state: "Bihar",
    languages: JSON.stringify(["Hindi", "Bhojpuri", "English", "Maithili"]),
    consultation_fee: 549,
    rating: 4.7,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 6:00 PM",
    photo_url: "",
    bio: "Urinary and reproductive health specialist with 15+ years experience.",
    is_online: 1
  },
  {
    name: "Dr. Kavya Nair",
    specialization: "General Physician",
    qualification: "MBBS, MD",
    experience_years: 6,
    hospital: "District Hospital",
    location: "Thiruvananthapuram, Kerala",
    state: "Kerala",
    languages: JSON.stringify(["Malayalam", "English", "Tamil"]),
    consultation_fee: 199,
    rating: 4.5,
    total_reviews: 334,
    available_today: 1,
    next_slot: "Today 2:30 PM",
    photo_url: "",
    bio: "Primary care doctor serving rural communities with affordable care.",
    is_online: 1
  },
  {
    name: "Dr. Abhishek Sharma",
    specialization: "Cardiologist",
    qualification: "MBBS, DM Cardiology",
    experience_years: 13,
    hospital: "Metro Hospital",
    location: "Noida, Uttar Pradesh",
    state: "Uttar Pradesh",
    languages: JSON.stringify(["Hindi", "English"]),
    consultation_fee: 749,
    rating: 4.7,
    total_reviews: 1123,
    available_today: 1,
    next_slot: "Today 4:45 PM",
    photo_url: "",
    bio: "Heart specialist focusing on preventive cardiology.",
    is_online: 1
  },
  {
    name: "Dr. Jasmine Kaur",
    specialization: "Pediatrician",
    qualification: "MBBS, MD Pediatrics",
    experience_years: 8,
    hospital: "Guru Nanak Hospital",
    location: "Amritsar, Punjab",
    state: "Punjab",
    languages: JSON.stringify(["Punjabi", "Hindi", "English"]),
    consultation_fee: 379,
    rating: 4.8,
    total_reviews: 556,
    available_today: 1,
    next_slot: "Today 3:00 PM",
    photo_url: "",
    bio: "Child health specialist with gentle approach to pediatric care.",
    is_online: 1
  },
  {
    name: "Dr. Raghavendra Rao",
    specialization: "Orthopedic Surgeon",
    qualification: "MBBS, MS Ortho, Fellowship in Arthroscopy",
    experience_years: 21,
    hospital: "Sunrise Hospital",
    location: "Mysore, Karnataka",
    state: "Karnataka",
    languages: JSON.stringify(["Kannada", "English", "Hindi", "Telugu"]),
    consultation_fee: 799,
    rating: 4.9,
    total_reviews: 1567,
    available_today: 0,
    next_slot: "Tomorrow 9:00 AM",
    photo_url: "/images/Dr.+Raghavendra+Rao.png",
    bio: "Senior orthopedic surgeon specializing in sports injuries and arthroscopy.",
    is_online: 0
  },
  {
    name: "Dr. Nisha Patel",
    specialization: "Dermatologist",
    qualification: "MBBS, MD Dermatology",
    experience_years: 11,
    hospital: "Skin Care Clinic",
    location: "Surat, Gujarat",
    state: "Gujarat",
    languages: JSON.stringify(["Gujarati", "Hindi", "English"]),
    consultation_fee: 449,
    rating: 4.7,
    total_reviews: 1345,
    available_today: 1,
    next_slot: "Today 5:15 PM",
    photo_url: "",
    bio: "Cosmetic dermatologist offering advanced skin treatments.",
    is_online: 1
  },
  {
    name: "Dr. Surya Prakash",
    specialization: "Neurologist",
    qualification: "MBBS, DM Neurology",
    experience_years: 14,
    hospital: "Neuro Care Center",
    location: "Bhopal, Madhya Pradesh",
    state: "Madhya Pradesh",
    languages: JSON.stringify(["Hindi", "English"]),
    consultation_fee: 699,
    rating: 4.6,
    total_reviews: 445,
    available_today: 1,
    next_slot: "Today 6:30 PM",
    photo_url: "",
    bio: "Neurophysician treating stroke, epilepsy, and movement disorders.",
    is_online: 1
  },
  {
    name: "Dr. Madhuri Dixit",
    specialization: "Gynecologist",
    qualification: "MBBS, MS OBG, Fellowship in IVF",
    experience_years: 16,
    hospital: "Mother Care Hospital",
    location: "Nagpur, Maharashtra",
    state: "Maharashtra",
    languages: JSON.stringify(["Marathi", "Hindi", "English"]),
    consultation_fee: 549,
    rating: 4.8,
    total_reviews: 2234,
    available_today: 1,
    next_slot: "Today 7:30 PM",
    photo_url: "",
    bio: "Fertility specialist with high success rate in IVF treatments.",
    is_online: 1
  },
  {
    name: "Dr. Ravi Shankar",
    specialization: "Diabetologist",
    qualification: "MBBS, MD Internal Medicine, CCEBDM",
    experience_years: 12,
    hospital: "Diabetes Care Center",
    location: "Ranchi, Jharkhand",
    state: "Jharkhand",
    languages: JSON.stringify(["Hindi", "English", "Santhali"]),
    consultation_fee: 329,
    rating: 4.7,
    total_reviews: 667,
    available_today: 1,
    next_slot: "Today 4:00 PM",
    photo_url: "",
    bio: "Certified diabetes educator helping patients achieve better glycemic control.",
    is_online: 1
  }
];

const hospitals = [
  {
    name: "Apollo Hospitals Chennai",
    location: "Greams Road, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    phone: "044-28290200",
    emergency_available: 1,
    total_beds: 500,
    available_beds: 47,
    icu_total: 80,
    icu_available: 12,
    ventilators_total: 40,
    ventilators_available: 6,
    specialties: JSON.stringify(["Cardiology", "Oncology", "Neurology", "Orthopedics", "Transplant"]),
    rating: 4.7,
    last_updated: new Date().toISOString()
  },
  {
    name: "AIIMS New Delhi",
    location: "Ansari Nagar, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    lat: 28.5665,
    lng: 77.2100,
    phone: "011-26588500",
    emergency_available: 1,
    total_beds: 2400,
    available_beds: 312,
    icu_total: 200,
    icu_available: 23,
    ventilators_total: 100,
    ventilators_available: 8,
    specialties: JSON.stringify(["All Specialties", "Super Specialties", "Research"]),
    rating: 4.9,
    last_updated: new Date().toISOString()
  },
  {
    name: "Lilavati Hospital Mumbai",
    location: "Bandra West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.0509,
    lng: 72.8296,
    phone: "022-26751000",
    emergency_available: 1,
    total_beds: 320,
    available_beds: 28,
    icu_total: 50,
    icu_available: 7,
    ventilators_total: 25,
    ventilators_available: 3,
    specialties: JSON.stringify(["Cardiology", "Oncology", "Nephrology", "Gastroenterology"]),
    rating: 4.8,
    last_updated: new Date().toISOString()
  },
  {
    name: "Fortis Hospital Bangalore",
    location: "Bannerghatta Road, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.8959,
    lng: 77.5998,
    phone: "080-66214444",
    emergency_available: 1,
    total_beds: 400,
    available_beds: 45,
    icu_total: 60,
    icu_available: 9,
    ventilators_total: 30,
    ventilators_available: 4,
    specialties: JSON.stringify(["Cardiology", "Neurology", "Orthopedics", "Urology"]),
    rating: 4.7,
    last_updated: new Date().toISOString()
  },
  {
    name: "Care Hospital Hyderabad",
    location: "Banjara Hills, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.4126,
    lng: 78.4221,
    phone: "040-30417777",
    emergency_available: 1,
    total_beds: 450,
    available_beds: 52,
    icu_total: 70,
    icu_available: 11,
    ventilators_total: 35,
    ventilators_available: 5,
    specialties: JSON.stringify(["Cardiology", "Neurosciences", "Orthopedics", "Gastroenterology"]),
    rating: 4.6,
    last_updated: new Date().toISOString()
  },
  {
    name: "AMRI Hospital Kolkata",
    location: "Dhakuria, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.5180,
    lng: 88.3652,
    phone: "033-24612626",
    emergency_available: 1,
    total_beds: 380,
    available_beds: 34,
    icu_total: 55,
    icu_available: 8,
    ventilators_total: 28,
    ventilators_available: 4,
    specialties: JSON.stringify(["Cardiology", "Oncology", "Nephrology", "Neurology"]),
    rating: 4.5,
    last_updated: new Date().toISOString()
  },
  {
    name: "Ruby Hall Clinic Pune",
    location: "Sassoon Road, Pune",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5293,
    lng: 73.8728,
    phone: "020-26163391",
    emergency_available: 1,
    total_beds: 350,
    available_beds: 41,
    icu_total: 45,
    icu_available: 6,
    ventilators_total: 22,
    ventilators_available: 3,
    specialties: JSON.stringify(["Cardiology", "Oncology", "Orthopedics", "Neurosurgery"]),
    rating: 4.7,
    last_updated: new Date().toISOString()
  },
  {
    name: "Sterling Hospital Ahmedabad",
    location: "Gurukul, Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0396,
    lng: 72.5112,
    phone: "079-40011111",
    emergency_available: 1,
    total_beds: 280,
    available_beds: 31,
    icu_total: 40,
    icu_available: 5,
    ventilators_total: 20,
    ventilators_available: 2,
    specialties: JSON.stringify(["Cardiology", "Neurology", "Nephrology", "Gastroenterology"]),
    rating: 4.6,
    last_updated: new Date().toISOString()
  },
  {
    name: "Narayana Health Jaipur",
    location: "Malviya Nagar, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.8500,
    lng: 75.8000,
    phone: "0141-4515151",
    emergency_available: 1,
    total_beds: 300,
    available_beds: 38,
    icu_total: 48,
    icu_available: 7,
    ventilators_total: 24,
    ventilators_available: 3,
    specialties: JSON.stringify(["Cardiology", "Oncology", "Orthopedics", "Pediatrics"]),
    rating: 4.5,
    last_updated: new Date().toISOString()
  },
  {
    name: "King George Hospital Lucknow",
    location: "Chowk, Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.8500,
    lng: 80.9500,
    phone: "0522-2257540",
    emergency_available: 1,
    total_beds: 600,
    available_beds: 89,
    icu_total: 90,
    icu_available: 14,
    ventilators_total: 45,
    ventilators_available: 6,
    specialties: JSON.stringify(["All Specialties", "Emergency Medicine", "Trauma Care"]),
    rating: 4.4,
    last_updated: new Date().toISOString()
  },
  {
    name: "Hamidia Hospital Bhopal",
    location: "Royal Market, Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    phone: "0755-2540090",
    emergency_available: 1,
    total_beds: 450,
    available_beds: 67,
    icu_total: 65,
    icu_available: 10,
    ventilators_total: 32,
    ventilators_available: 4,
    specialties: JSON.stringify(["General Medicine", "Surgery", "Pediatrics", "Gynecology"]),
    rating: 4.3,
    last_updated: new Date().toISOString()
  },
  {
    name: "Christian Medical College Ludhiana",
    location: "Brown Road, Ludhiana",
    city: "Ludhiana",
    state: "Punjab",
    lat: 30.9000,
    lng: 75.8500,
    phone: "0161-2603070",
    emergency_available: 1,
    total_beds: 850,
    available_beds: 112,
    icu_total: 120,
    icu_available: 18,
    ventilators_total: 60,
    ventilators_available: 9,
    specialties: JSON.stringify(["All Specialties", "Hematology", "Oncology", "Transplant"]),
    rating: 4.8,
    last_updated: new Date().toISOString()
  },
  {
    name: "Kerala Institute of Medical Sciences",
    location: "Anayara, Trivandrum",
    city: "Thiruvananthapuram",
    state: "Kerala",
    lat: 8.5241,
    lng: 76.9366,
    phone: "0471-3041000",
    emergency_available: 1,
    total_beds: 650,
    available_beds: 78,
    icu_total: 85,
    icu_available: 12,
    ventilators_total: 42,
    ventilators_available: 6,
    specialties: JSON.stringify(["Cardiology", "Neurology", "Nephrology", "Gastroenterology"]),
    rating: 4.6,
    last_updated: new Date().toISOString()
  },
  {
    name: "IMS BHU Varanasi",
    location: "Lanka, Varanasi",
    city: "Varanasi",
    state: "Uttar Pradesh",
    lat: 25.3176,
    lng: 82.9739,
    phone: "0542-2367568",
    emergency_available: 1,
    total_beds: 1800,
    available_beds: 234,
    icu_total: 150,
    icu_available: 22,
    ventilators_total: 75,
    ventilators_available: 11,
    specialties: JSON.stringify(["All Specialties", "Super Specialties", "Ayurveda Integration"]),
    rating: 4.5,
    last_updated: new Date().toISOString()
  },
  {
    name: "SCB Medical College Cuttack",
    location: "Mangalabag, Cuttack",
    city: "Cuttack",
    state: "Odisha",
    lat: 20.4625,
    lng: 85.8830,
    phone: "0671-2414080",
    emergency_available: 1,
    total_beds: 1100,
    available_beds: 145,
    icu_total: 95,
    icu_available: 14,
    ventilators_total: 48,
    ventilators_available: 7,
    specialties: JSON.stringify(["All Specialties", "Trauma Care", "Burn Unit"]),
    rating: 4.4,
    last_updated: new Date().toISOString()
  },
  {
    name: "NIMS Hyderabad",
    location: "Panjagutta, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.4156,
    lng: 78.4576,
    phone: "040-23489000",
    emergency_available: 1,
    total_beds: 950,
    available_beds: 123,
    icu_total: 110,
    icu_available: 16,
    ventilators_total: 55,
    ventilators_available: 8,
    specialties: JSON.stringify(["All Specialties", "Nephrology", "Urology", "Neurosciences"]),
    rating: 4.6,
    last_updated: new Date().toISOString()
  },
  {
    name: "Sawai Man Singh Hospital",
    location: "Jawahar Lal Nehru Marg, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9033,
    lng: 75.8157,
    phone: "0141-2560291",
    emergency_available: 1,
    total_beds: 2000,
    available_beds: 267,
    icu_total: 180,
    icu_available: 26,
    ventilators_total: 90,
    ventilators_available: 13,
    specialties: JSON.stringify(["All Specialties", "Trauma Center", "Burn Center"]),
    rating: 4.5,
    last_updated: new Date().toISOString()
  },
  {
    name: "JIPMER Puducherry",
    location: "Gorimedu, Puducherry",
    city: "Puducherry",
    state: "Puducherry",
    lat: 11.9416,
    lng: 79.8083,
    phone: "0413-2272380",
    emergency_available: 1,
    total_beds: 3000,
    available_beds: 412,
    icu_total: 250,
    icu_available: 37,
    ventilators_total: 125,
    ventilators_available: 18,
    specialties: JSON.stringify(["All Specialties", "Research", "Medical Education"]),
    rating: 4.8,
    last_updated: new Date().toISOString()
  },
  {
    name: "Gauhati Medical College",
    location: "Bhangagarh, Guwahati",
    city: "Guwahati",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    phone: "0361-2524555",
    emergency_available: 1,
    total_beds: 1200,
    available_beds: 156,
    icu_total: 100,
    icu_available: 15,
    ventilators_total: 50,
    ventilators_available: 7,
    specialties: JSON.stringify(["All Specialties", "Neurosciences", "Cardiology"]),
    rating: 4.4,
    last_updated: new Date().toISOString()
  },
  {
    name: "Rajendra Hospital Patiala",
    location: "Sangrur Road, Patiala",
    city: "Patiala",
    state: "Punjab",
    lat: 30.3398,
    lng: 76.3869,
    phone: "0175-2212000",
    emergency_available: 1,
    total_beds: 700,
    available_beds: 89,
    icu_total: 80,
    icu_available: 12,
    ventilators_total: 40,
    ventilators_available: 6,
    specialties: JSON.stringify(["All Specialties", "Cardiology", "Nephrology"]),
    rating: 4.3,
    last_updated: new Date().toISOString()
  }
];

// Insert doctors
doctors.forEach(doctor => {
  db.doctors.create(doctor);
});

console.log(`âœ… Inserted ${doctors.length} doctors`);

// Insert hospitals
hospitals.forEach(hospital => {
  db.hospitals.create(hospital);
});

console.log(`âœ… Inserted ${hospitals.length} hospitals`);

console.log('\nðŸŒ± Database seeding completed successfully!');
console.log('Run "npm start" to start the server.');
